_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 77
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 77
                - 103
            "3":
                - 1
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
